"""empty message

Revision ID: e5f99d2d3fc3
Revises: 56b71297e22f
Create Date: 2023-05-24 17:13:55.483313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5f99d2d3fc3'
down_revision = '56b71297e22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('machine_serial_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('intervention_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('open_ticket_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('open_ticket_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('intervention_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('machine_serial_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
